### ISSUE TITLE
Suggested rewrite of summary

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/redux-flow#10]
This sentence:
"So to change our state we (1) create an action, an action is just a plain object with a type key (2) and pass the action as an argument when we call the reducer, which is just a function with a switch/case statement, which (3) produces a new state."

...would make more sense this way:
"So to change our state we (1) create an action (an action is just a plain object with a type key); and (2) and pass the action as an argument when we call the reducer (which is just a function with a switch/case statement). This produces a new state."

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for providing this feedback. I've updated the summary using your suggested text.
