### ISSUE TITLE
Missing colon on code snippet

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/redux-flow#9]
Missing a colon after 'DECREASE_COUNT'

`function reducer(state, action){      
  switch (action.type) {
    case 'INCREASE_COUNT':
      return {count: state.count + 1}
    case 'DECREASE_COUNT'
      return {count: state.count - 1}
    default:
      return state;
  }
}`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
